// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVxGcOo4b7vI9IzoVgDsd5JRf-gnhUz0c',
    appId: '1:799419299310:web:8510649efea75754e40aff',
    messagingSenderId: '799419299310',
    projectId: 'donation-app-76afd',
    authDomain: 'donation-app-76afd.firebaseapp.com',
    storageBucket: 'donation-app-76afd.appspot.com',
    measurementId: 'G-KEKSV5261H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwTvzsQI72mf7oYM_G4Qgd1JPyTESQgi8',
    appId: '1:799419299310:android:759d4c520ef80356e40aff',
    messagingSenderId: '799419299310',
    projectId: 'donation-app-76afd',
    storageBucket: 'donation-app-76afd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVwrA2mCgS1OwJr7Qxkd5Zqj5R51nh_9A',
    appId: '1:799419299310:ios:bdeee2e1d59d0a74e40aff',
    messagingSenderId: '799419299310',
    projectId: 'donation-app-76afd',
    storageBucket: 'donation-app-76afd.appspot.com',
    androidClientId: '799419299310-rmlkc3itjitc8jst2ppb4c21hjc01t34.apps.googleusercontent.com',
    iosClientId: '799419299310-dcka7hdilhrdeqsi8r1gjmrr206297fm.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiplatformDonationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVwrA2mCgS1OwJr7Qxkd5Zqj5R51nh_9A',
    appId: '1:799419299310:ios:67d624058b26b5ece40aff',
    messagingSenderId: '799419299310',
    projectId: 'donation-app-76afd',
    storageBucket: 'donation-app-76afd.appspot.com',
    androidClientId: '799419299310-rmlkc3itjitc8jst2ppb4c21hjc01t34.apps.googleusercontent.com',
    iosClientId: '799419299310-3fh4kahubmbi7du24v1kgkca4t504jp9.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiplatformDonationApp.RunnerTests',
  );
}
